Attribute VB_Name = "Constants"
'-------------------------------------------------------------------------------
' Name:        Constants (Module)
' Purpose:     Defines auxiliary constant variables and functions
'
' Author:      Brian Skinn
'                bskinn@alum.mit.edu
'
' Created:     30 Apr 2016
' Copyright:   (c) Brian Skinn 2016
' License:     The MIT License; see "license.txt" for full license terms
'                   and contributor agreement.
'
'       This file is part of ORCA Importer, an Excel VBA add-in providing
'       memoized import functionality for output generated by the ORCA
'       quantum chemistry software program package
'       (http://orcaforum.cec.mpg.de).
'
'       http://www.github.com/bskinn/excel-orcaimport
'
'-------------------------------------------------------------------------------

Option Explicit
Option Base 1

Public Enum DispDirection
    dispUninitialized = -1000
    dispPositive = 1
    dispNone = 0
    dispNegative = -1
End Enum

Public Enum ENGRAD_DATA_TYPE
    gradGradient = 1
    '...
End Enum

Public Enum HESS_DATA_TYPE
    hessHessian = 1
    hessModes = 2
    hessFreqs = 3
    hessWeights = 4
    hessWtsMatrix = 5
    hessRootWtsMatrix = 6
    hessRootInvWtsMatrix = 7
    hessModesUnweighted = 8
    '...
End Enum

Public Enum XYZ_DATA_TYPE
    xyzSingleGeom = 1
    xyzAtomicNums = 2
    xyzExpandedAtNums = 3
    xyzAtomicSyms = 4
    xyzExpandedAtSyms = 5
    xyzAtomCoords = 6
    xyzGeomComments = 7
    xyzBondDistance = 8
    '...
End Enum

Public Enum MassPerturbation
    mpUninitialized = -1000
    mpNone = 1
    mpByAtom = 2
    mpByCoord = 3
End Enum

Public Enum MolecularTopType
    topUninitialized = -1000
    topInvalid = -500
    topAtom = 1
    topLinear = 2
    topSpherical = 3
    topSymmetricalProlate = 4
    topSymmetricalOblate = 5
    topAsymmetrical = 6
End Enum

Public Enum RotConstUnits
    rcuInvInertia = 1           ' mu/2              -- inverse inertial moment
    rcuAngFreqAtomic = 2        ' hbar*mu/2         -- Angular frequency, inverse atomic time unit (Ta)
    rcuAngFreqSeconds = 3       '  (same)           --    "        "    , inverse seconds
    rcuCyclicFreqAtomic = 4     ' hbar*mu/(2*2pi)   -- Cyclic frequency, cycles per Ta
    rcuCyclicFreqSeconds = 5    '  (same)           --    "       "    , cycles per s
    rcuCyclicFreqMHz = 6        '  (same)           --    "       "    , MHz (10^6 cycles per s)
    rcuWaveNumAtomic = 7        ' hbar*mu/(2*2pi*c) -- Wavenumber, cycles per Bohr
    rcuWaveNumCm = 8            '  (same)           --      "    , cycles per cm
End Enum

Public Enum vectorDirection
    vdColVector = 1
    vdRowVector = 2
End Enum

Public Enum mtxSpec
    ' Enumerates the types of dimension data stored for an array by
    '  Utility.mtxSpecs
    msLB1 = 1
    msUB1 = 2
    msLB2 = 3
    msUB2 = 4
    msDim1 = 5
    msDim2 = 6
    msNumEl = 7
End Enum

' Execution/compilation control constants
Public Const DEBUG__MODE__ = True

' Code information constants
Public Const Invalid_Atom_Symbol As Long = -1
Public Const Unsupported_Atomic_Number As String = "INVALID"
Public Const Failed_Import_Str As String = "Import Failed"
Public Const Max_Atomic_Num As Long = 103
Public Const Min_Atomic_Num As Long = 1
Public Const RandBetween_Range As Double = 1000000#

' Physical constants
Public Const Angs_per_Bohr As Double = 0.5291772
Public Const AMU_per_me As Double = 1822.89
Public Const Seconds_per_Atomic_Time As Double = 2.4188843265E-17
Public Const Speed_of_Light As Double = 137.082
Public Const Planck_Constant As Double = 6.28318531
Public Const Planck_Slash As Double = 1#


' Simulation parameter values/defaults
Public Const DEF_Mass_Perturbation_Magnitude As Double = 0.0001
Public Const DEF_Moment_Tol As Double = 0.0001
Public Const DEF_Orthonorm_Tol As Double = 0.00000001
Public Const PRM_Non_Parallel_Tol As Double = 0.001

' Uninitialized value constants
Public Const Uninit_Unsigned_Long As Long = -1
Public Const Uninit_Unsigned_Dbl As Double = -1#
' These two below are potentially fragile, but should never occur in real simulations?
' No tractable number of atoms could get this high, nor any tractable number of modes
Public Const Uninit_Signed_Long As Long = 1234567890
' No energy should be this positive, nor any geometry, gradient element, or Hessian element
Public Const Uninit_Signed_Dbl As Double = 1234567890.12345

Public Function atomNum(ByVal atomSymbol As String) As Long
    Select Case UCase(atomSymbol)
    Case "H"
        atomNum = 1
    Case "HE"
        atomNum = 2
    Case "LI"
        atomNum = 3
    Case "BE"
        atomNum = 4
    Case "B"
        atomNum = 5
    Case "C"
        atomNum = 6
    Case "N"
        atomNum = 7
    Case "O"
        atomNum = 8
    Case "F"
        atomNum = 9
    Case "NE"
        atomNum = 10
    Case "NA"
        atomNum = 11
    Case "MG"
        atomNum = 12
    Case "AL"
        atomNum = 13
    Case "SI"
        atomNum = 14
    Case "P"
        atomNum = 15
    Case "S"
        atomNum = 16
    Case "CL"
        atomNum = 17
    Case "AR"
        atomNum = 18
    Case "K"
        atomNum = 19
    Case "CA"
        atomNum = 20
    Case "SC"
        atomNum = 21
    Case "TI"
        atomNum = 22
    Case "V"
        atomNum = 23
    Case "CR"
        atomNum = 24
    Case "MN"
        atomNum = 25
    Case "FE"
        atomNum = 26
    Case "CO"
        atomNum = 27
    Case "NI"
        atomNum = 28
    Case "CU"
        atomNum = 29
    Case "ZN"
        atomNum = 30
    Case "GA"
        atomNum = 31
    Case "GE"
        atomNum = 32
    Case "AS"
        atomNum = 33
    Case "SE"
        atomNum = 34
    Case "BR"
        atomNum = 35
    Case "KR"
        atomNum = 36
    Case "RB"
        atomNum = 37
    Case "SR"
        atomNum = 38
    Case "Y"
        atomNum = 39
    Case "ZR"
        atomNum = 40
    Case "NB"
        atomNum = 41
    Case "MO"
        atomNum = 42
    Case "TC"
        atomNum = 43
    Case "RU"
        atomNum = 44
    Case "RH"
        atomNum = 45
    Case "PD"
        atomNum = 46
    Case "AG"
        atomNum = 47
    Case "CD"
        atomNum = 48
    Case "IN"
        atomNum = 49
    Case "SN"
        atomNum = 50
    Case "SB"
        atomNum = 51
    Case "TE"
        atomNum = 52
    Case "I"
        atomNum = 53
    Case "XE"
        atomNum = 54
    Case "CS"
        atomNum = 55
    Case "BA"
        atomNum = 56
    Case "LA"
        atomNum = 57
    Case "CE"
        atomNum = 58
    Case "PR"
        atomNum = 59
    Case "ND"
        atomNum = 60
    Case "PM"
        atomNum = 61
    Case "SM"
        atomNum = 62
    Case "EU"
        atomNum = 63
    Case "GD"
        atomNum = 64
    Case "TB"
        atomNum = 65
    Case "DY"
        atomNum = 66
    Case "HO"
        atomNum = 67
    Case "ER"
        atomNum = 68
    Case "TM"
        atomNum = 69
    Case "YB"
        atomNum = 70
    Case "LU"
        atomNum = 71
    Case "HF"
        atomNum = 72
    Case "TA"
        atomNum = 73
    Case "W"
        atomNum = 74
    Case "RE"
        atomNum = 75
    Case "OS"
        atomNum = 76
    Case "IR"
        atomNum = 77
    Case "PT"
        atomNum = 78
    Case "AU"
        atomNum = 79
    Case "HG"
        atomNum = 80
    Case "TL"
        atomNum = 81
    Case "PB"
        atomNum = 82
    Case "BI"
        atomNum = 83
    Case "PO"
        atomNum = 84
    Case "AT"
        atomNum = 85
    Case "RN"
        atomNum = 86
    Case "FR"
        atomNum = 87
    Case "RA"
        atomNum = 88
    Case "AC"
        atomNum = 89
    Case "TH"
        atomNum = 90
    Case "PA"
        atomNum = 91
    Case "U"
        atomNum = 92
    Case "NP"
        atomNum = 93
    Case "PU"
        atomNum = 94
    Case "AM"
        atomNum = 95
    Case "CM"
        atomNum = 96
    Case "BK"
        atomNum = 97
    Case "CF"
        atomNum = 98
    Case "ES"
        atomNum = 99
    Case "FM"
        atomNum = 100
    Case "MD"
        atomNum = 101
    Case "NO"
        atomNum = 102
    Case "LR"
        atomNum = 103
    Case Else
        atomNum = Invalid_Atom_Symbol
    End Select
End Function

Public Function atomSym(ByVal atomNumber As Long) As String
    Select Case atomNumber
    Case 1
        atomSym = "H"
    Case 2
        atomSym = "He"
    Case 3
        atomSym = "Li"
    Case 4
        atomSym = "Be"
    Case 5
        atomSym = "B"
    Case 6
        atomSym = "C"
    Case 7
        atomSym = "N"
    Case 8
        atomSym = "O"
    Case 9
        atomSym = "F"
    Case 10
        atomSym = "Ne"
    Case 11
        atomSym = "Na"
    Case 12
        atomSym = "Mg"
    Case 13
        atomSym = "Al"
    Case 14
        atomSym = "Si"
    Case 15
        atomSym = "P"
    Case 16
        atomSym = "S"
    Case 17
        atomSym = "Cl"
    Case 18
        atomSym = "Ar"
    Case 19
        atomSym = "K"
    Case 20
        atomSym = "Ca"
    Case 21
        atomSym = "Sc"
    Case 22
        atomSym = "Ti"
    Case 23
        atomSym = "V"
    Case 24
        atomSym = "Cr"
    Case 25
        atomSym = "Mn"
    Case 26
        atomSym = "Fe"
    Case 27
        atomSym = "Co"
    Case 28
        atomSym = "Ni"
    Case 29
        atomSym = "Cu"
    Case 30
        atomSym = "Zn"
    Case 31
        atomSym = "Ga"
    Case 32
        atomSym = "Ge"
    Case 33
        atomSym = "As"
    Case 34
        atomSym = "Se"
    Case 35
        atomSym = "Br"
    Case 36
        atomSym = "Kr"
    Case 37
        atomSym = "Rb"
    Case 38
        atomSym = "Sr"
    Case 39
        atomSym = "Y"
    Case 40
        atomSym = "Zr"
    Case 41
        atomSym = "Nb"
    Case 42
        atomSym = "Mo"
    Case 43
        atomSym = "Tc"
    Case 44
        atomSym = "Ru"
    Case 45
        atomSym = "Rh"
    Case 46
        atomSym = "Pd"
    Case 47
        atomSym = "Ag"
    Case 48
        atomSym = "Cd"
    Case 49
        atomSym = "In"
    Case 50
        atomSym = "Sn"
    Case 51
        atomSym = "Sb"
    Case 52
        atomSym = "Te"
    Case 53
        atomSym = "I"
    Case 54
        atomSym = "Xe"
    Case 55
        atomSym = "Cs"
    Case 56
        atomSym = "Ba"
    Case 57
        atomSym = "La"
    Case 58
        atomSym = "Ce"
    Case 59
        atomSym = "Pr"
    Case 60
        atomSym = "Nd"
    Case 61
        atomSym = "Pm"
    Case 62
        atomSym = "Sm"
    Case 63
        atomSym = "Eu"
    Case 64
        atomSym = "Gd"
    Case 65
        atomSym = "Tb"
    Case 66
        atomSym = "Dy"
    Case 67
        atomSym = "Ho"
    Case 68
        atomSym = "Er"
    Case 69
        atomSym = "Tm"
    Case 70
        atomSym = "Yb"
    Case 71
        atomSym = "Lu"
    Case 72
        atomSym = "Hf"
    Case 73
        atomSym = "Ta"
    Case 74
        atomSym = "W"
    Case 75
        atomSym = "Re"
    Case 76
        atomSym = "Os"
    Case 77
        atomSym = "Ir"
    Case 78
        atomSym = "Pt"
    Case 79
        atomSym = "Au"
    Case 80
        atomSym = "Hg"
    Case 81
        atomSym = "Tl"
    Case 82
        atomSym = "Pb"
    Case 83
        atomSym = "Bi"
    Case 84
        atomSym = "Po"
    Case 85
        atomSym = "At"
    Case 86
        atomSym = "Rn"
    Case 87
        atomSym = "Fr"
    Case 88
        atomSym = "Ra"
    Case 89
        atomSym = "Ac"
    Case 90
        atomSym = "Th"
    Case 91
        atomSym = "Pa"
    Case 92
        atomSym = "U"
    Case 93
        atomSym = "Np"
    Case 94
        atomSym = "Pu"
    Case 95
        atomSym = "Am"
    Case 96
        atomSym = "Cm"
    Case 97
        atomSym = "Bk"
    Case 98
        atomSym = "Cf"
    Case 99
        atomSym = "Es"
    Case 100
        atomSym = "Fm"
    Case 101
        atomSym = "Md"
    Case 102
        atomSym = "No"
    Case 103
        atomSym = "Lr"
    Case Else
        atomSym = Unsupported_Atomic_Number
    End Select
End Function
